### ISSUE TITLE
UI stuck on address book import (no progress)

### ISSUE THREAD

**Issue by ghost** [open-xchange/flutter-deltachat-core#45]
**Description**
When importing the address book the app stuck on the progress overlay. There isn't any progress visible, but the contacts are imported. Overlay doesn't disappear which results in an overall blocked UI.

**Tested on**
 - Simulator: iPhone 8, iPhone XR and iPhone XS
 - Device: iPhone 7
 - OS: iOS 12.4, iOS 13.1

[Internal Bugtracker](https://jira.open-xchange.com/browse/OT-479)

**Comment by Boehrsi** [comment]
Moved this issue to the plugin project, as this is fixed within the plugin context.
