### ISSUE TITLE
Add method to set and get the duration.

### ISSUE THREAD

**Issue by florianhaar** [open-xchange/flutter-deltachat-core#63]
**Describe the solution you'd like**
Make sure that the methods to set and get the duration are in the iOS classes.
For the Dc_Msg add:
- DcMsg_getDuration

and for the context_createChatAttachmentMessage add setDuration(duration) for the new DcMsg.
Android part:
```
DcMsg newMsg = new DcMsg(dcContext, type);
newMsg.setFile(path, mimeType);
newMsg.setText(text);
newMsg.setDuration(duration);
int messageId = dcContext.sendMsg(chatId, newMsg);
```
[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-538)

**Comment by Boehrsi** [comment]
Fixed by https://github.com/open-xchange/flutter-deltachat-core/commit/b88f4ebfb0effb457d12c7a72fe00e9dbea0dde3
