### ISSUE TITLE
Android build is unable to send files

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/flutter-deltachat-core#71]
**Describe the bug**
Due to problems with the used PGP library we are currently unable to build a well working Android version. This issue blocks a new release for the Android version. The symptom of this problem is a bricked app, as soon as a file is received. 

**Additional context**
To fix this we will apply a temporary fix in our build script, which changes the PGP dependency on the fly, until the problem itself is fixed.

**Comment by Boehrsi** [comment]
Added the warning label as this issue is urgent.

**Comment by florianhaar** [comment]
The workaround was merged.
